version: '3.8'

services:
  database:
    image: postgres:14
    container_name: database
    ports:
      - ${PGPORT}:${PGPORT}
    network_mode: host
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: ${PGHOST}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - auth-database:/var/lib/postgresql/data
    restart: always

  redis:
    image: "redis:7.2.4-alpine"
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    network_mode: host
    env_file:
      - ../.env
    volumes:
      - redis-data:/data

  auth-app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: auth-app
    network_mode: host
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ../.env
    depends_on:
      - database
      - redis
    restart: always
volumes:
  auth-database:
  redis-data: